//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Azure.CCME.Assessment.Managers.ReportGenerators {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PdfReportMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PdfReportMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Azure.CCME.Assessment.Managers.ReportGenerators.PdfReportMessages", typeof(PdfReportMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consideration.
        /// </summary>
        internal static string ConsiderationBookmark {
            get {
                return ResourceManager.GetString("ConsiderationBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;According to the \&quot;Internet Information Services\&quot; regulation, the \&quot;non - commercial Internet information service record management\&quot; regulation, and the other regulations promulgated by the Ministry of China, the government has enforced all non-commercial Internet information services to strictly follow the ICP (Internet Content Provider) registration and filing process.&quot;.
        /// </summary>
        internal static string ConsiderationICPContent_P1 {
            get {
                return ResourceManager.GetString("ConsiderationICPContent_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To obtain an ICP license from China&apos;s Ministry of Industry and Information Technology (MIIT), you must follow the ICP registration and filing process. Before you begin the process, you must first have a legal presence in China, and you should have your own ICP license for your website..
        /// </summary>
        internal static string ConsiderationICPContent_P2 {
            get {
                return ResourceManager.GetString("ConsiderationICPContent_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICP License.
        /// </summary>
        internal static string ConsiderationICPTitle {
            get {
                return ResourceManager.GetString("ConsiderationICPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consideration and Risk.
        /// </summary>
        internal static string ConsiderationTitle {
            get {
                return ResourceManager.GetString("ConsiderationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Understand what to migrate and to comprehend the migration outcome.
        /// </summary>
        internal static string IntroductionContent_ListItem1 {
            get {
                return ResourceManager.GetString("IntroductionContent_ListItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Identify the service and configuration gaps between the source and the destination environment and minimize the unexpected migration risks..
        /// </summary>
        internal static string IntroductionContent_ListItem2 {
            get {
                return ResourceManager.GetString("IntroductionContent_ListItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.	Estimate the cost in the destination environment for budget planning..
        /// </summary>
        internal static string IntroductionContent_ListItem3 {
            get {
                return ResourceManager.GetString("IntroductionContent_ListItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The aim of China Cloud Migration &amp; Expansion tool set is to ease the migration process for Global Azure customers while migrating/expanding their global solutions to Azure China, and vice versa. This report is part of the tool set offering..
        /// </summary>
        internal static string IntroductionContent_P1 {
            get {
                return ResourceManager.GetString("IntroductionContent_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The purpose of this report is to help customers to decide whether to perform migration by providing following information:.
        /// </summary>
        internal static string IntroductionContent_P2 {
            get {
                return ResourceManager.GetString("IntroductionContent_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China Cloud Migration &amp; Expansion Assessment Report.
        /// </summary>
        internal static string IntroductionTitle {
            get {
                return ResourceManager.GetString("IntroductionTitle", resourceCulture);
            }
        }
    }
}
